name: Check Container Digest Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
      tags:
        description: 'Manual trigger'  

jobs:
  check-digest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['stable', 'stable-tensorrt', 'stable-rocm', 'stable-standard-arm64']
    outputs:
      stable: ${{ steps.compare.outputs.stable }}
      stable-tensorrt: ${{ steps.compare.outputs.stable-tensorrt }}
      stable-rocm: ${{ steps.compare.outputs.stable-rocm }}
      stable-standard-arm64: ${{ steps.compare.outputs.stable-standard-arm64 }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get current digest
      id: digest
      run: |
        if [[ ${{ matrix.image }} == 'stable-standard-arm64' ]]; then
          arch=arm64
        else
          arch=amd64
        fi
        dg=$(skopeo inspect docker://ghcr.io/blakeblackshear/frigate:${{ matrix.image }} --override-arch=$arch --override-os=linux | jq -r '.Digest')
        echo "current_digest=$dg" >> $GITHUB_OUTPUT

    - name: Compare digests
      id: compare
      run: |
        digest_file="upstream_digests.txt"
        tag=${{ matrix.image }}
        new_digest=${{ steps.digest.outputs.current_digest }}

        # Read previous digest from file
        if [ -f "$digest_file" ]; then
          old_digest=$(grep "^$tag=" "$digest_file" | cut -d '=' -f2)
          if [ "$old_digest" != "$new_digest" ]; then
            echo "Digest changed for $tag"
            stat=changed
          else
            stat=unchanged
          fi
        else
          echo "First run or $digest_file file not found"
          stat=new
        fi
        echo "${tag}=${new_digest}:${stat}" >> $GITHUB_OUTPUT

  aggregate-results:
    needs: check-digest
    runs-on: ubuntu-latest
    outputs:
      changed-tags: ${{ steps.aggregate.outputs.changed_tags }}
      changed-digests: ${{ steps.aggregate.outputs.changed_digests }}
    steps:
    - name: Aggregate changed tags and digests
      id: aggregate
      run: |
        echo '${{ toJSON(needs.check-digest.outputs) }}'
        changed_tags=""
        changed_digests=""

        echo "changed_tags=${changed_tags%,}" >> $GITHUB_OUTPUT
        echo "changed_digests=${changed_digests%,}" >> $GITHUB_OUTPUT

  publish-digest:
    needs: aggregate-results
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.aggregate-results.outputs.changed-tags) }}
        digest: ${{ fromJson(needs.aggregate-results.outputs.changed-digests) }}
    steps:
    - name: test
      run: |
        echo ${{ matrix.tag }}
        echo ${{ matrix.digest }}